### ISSUE TITLE
pip download error

### ISSUE THREAD

**Issue by sebastianpfischer** [FreeGeronimo/autofff#2]
Hi Andreas,

seems like the pip install does not work as expected:
```bash
python -m pip install autofff
Collecting autofff
  Using cached https://files.pythonhosted.org/packages/fa/93/699704c1a277bd51e6f9c0577fa6ed585ec674f72a6533aa6ff61675ec9f/autofff-0.3-py3-none-any.whl
Collecting overrides>=1.9 (from autofff)
  Downloading https://files.pythonhosted.org/packages/de/55/3100c6d14c1ed177492fcf8f07c4a7d2d6c996c0a7fc6a9a0a41308e7eec/overrides-1.9.tar.gz
Collecting validator>=2.0.6 (from autofff)
  Using cached https://files.pythonhosted.org/packages/09/42/00e6244cdc62bbef3dcdfdbe8232e6960fcca2e7a501f0d74e5c6258b06e/validator-2.0.6.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/yanc/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
    Couldn't find index page for 'yanc' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
    No local packages or download links found for yanc==0.2.4
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\fsc6lr\AppData\Local\Temp\pip-build-r9e4eyy_\validator\setup.py", line 21, in <module>
        , 'yanc==0.2.4'
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\setuptools\dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\setuptools\dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\pkg_resources\__init__.py", line 836, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\pkg_resources\__init__.py", line 1081, in best_match
        return self.obtain(req, installer)
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\pkg_resources\__init__.py", line 1093, in obtain
        return installer(requirement)
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\setuptools\dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\CDDK_Example\Tools\Python\v3.4.4-1.1.0\lib\site-packages\setuptools\command\easy_install.py", line 623, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('yanc==0.2.4')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\fsc6lr\AppData\Local\Temp\pip-build-r9e4eyy_\validator
```

It also does not work with a manual installation "python -m pip install ."

I tried with anaconda3 with python 3.6 and a standalone python with python 3.4, both are not working...

Hope you can fix it ;P

**Comment by FreeGeronimo** [comment]
Download error on https://pypi.python.org/simple/yanc/: [Errno 11001] getaddrinfo failed -- Some packages may not be found!
It appears that pip could not resolve this address, could it be that you're being blocked by your company's proxy-server?
The package is required by the config `validator` package used by autofff, perhaps the `setup.py` there didn't take your proxy settings into account. Try manually installing `yanc` via `python -m pip install yanc==0.2.4 --proxy=<your proxy>:<proxy-port>`

Also please note that autofff currently targets >=Python3.6. You'll likely won't be able to run autofff with Python3.4 due to the use of format strings.

I'm honestly a bit supprised as I don't see `yanc` installed on my Windows or Linux workstation after a clean install of Python3.6 + autofff.

**Comment by FreeGeronimo** [comment]
not reproducible
